name: Next.js Cache
description: Restore and save Next.js incremental build cache (./next/cache)

inputs:
    path:
        description: Path to the .next/cache directory (e.g. apps/web/.next/cache)
        required: false
        default: apps/web/.next/cache

    lockfile-path:
        description: 'Path(s) to lockfile(s) used to derive part of the cache key'
        required: false
        default: pnpm-lock.yaml

runs:
    using: composite
    steps:
        - uses: actions/cache@v6
          with:
              path: ${{ inputs.path }}
              key: ${{ runner.os }}-nextjs-${{ hashFiles(inputs.lockfile-path) }}
